"""Add lots and absolute risk management to Strategy

Revision ID: c116955ad7d5
Revises: 
Create Date: 2025-06-19 00:36:41.556712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c116955ad7d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lots', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stop_loss_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('target_profit_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('call_security_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('put_security_id', sa.String(length=20), nullable=True))
        batch_op.drop_column('put_order_id')
        batch_op.drop_column('entry_premium')
        batch_op.drop_column('stop_loss_percent')
        batch_op.drop_column('target_profit_percent')
        batch_op.drop_column('call_order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('call_order_id', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('target_profit_percent', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('stop_loss_percent', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('entry_premium', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('put_order_id', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('put_security_id')
        batch_op.drop_column('call_security_id')
        batch_op.drop_column('target_profit_amount')
        batch_op.drop_column('stop_loss_amount')
        batch_op.drop_column('lots')

    # ### end Alembic commands ###
