"""Add product type and leg transaction types

Revision ID: df9491b6f34f
Revises: c116955ad7d5
Create Date: 2025-06-19 01:00:08.014691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9491b6f34f'
down_revision = 'c116955ad7d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('call_transaction_type', sa.String(length=4), nullable=False))
        batch_op.add_column(sa.Column('put_transaction_type', sa.String(length=4), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.drop_column('put_transaction_type')
        batch_op.drop_column('call_transaction_type')
        batch_op.drop_column('product_type')

    # ### end Alembic commands ###
